### ISSUE TITLE
Feature Request: Share button on the new tab

### ISSUE THREAD

**Issue by rpaul80** [planetlabs/planet-view#19]
I think a simple feature we can make to drive traffic to planet.com and downloads of the extension is to put a simple share button on the image. If we wanted to be fancy, we could potentially check if the user has twitter or facebook in their history, and, if present, display the facebook and/or twitter share there so we are not cluttering the UI with social channels they don't use.

User story is this:
As a user, when I see an image I like on a new tab with the Planet Chrome Extension, I want to be able to share it with my friends so they can see it as well.

**Comment by tschaub** [comment]
We had this at some point.  Now it is gone.
