### ISSUE TITLE
Factor out common parts and create Firefox extension

### ISSUE THREAD

**Issue by tschaub** [planetlabs/planet-view#38]
We can reuse the majority of this for a Firefox extension.  See [this post](https://mike.kaply.com/2012/06/21/best-practices-for-overriding-the-new-tab-page-with-your-extension/) for advice on overriding the new tab page in a Firefox extension.

**Comment by arky** [comment]
I had created a quick addon for Firefox here https://github.com/arky/planet-view-firefox-addon

However I am blocked by this error in the planet-view-chrome-ext. Looks like 3d.js error.

20:03:09.450 Cross-Origin Request Blocked: The Same Origin Policy
disallows reading the remote resource at
https://www.planet.com/gallery.json. (Reason: CORS header
'Access-Control-Allow-Origin' missing).1 <unknown>

**Comment by tschaub** [comment]
Thanks to @AndrewAnnex in #60, we now have a Firefox Add-on: https://addons.mozilla.org/en-US/firefox/addon/planet-view/
