### ISSUE TITLE
How do I uninstall the Chrome extension? 

### ISSUE THREAD

**Issue by RBourassa** [planetlabs/planet-view#45]
It doesn't show up as an extension or app, so I can't figure out how to uninstall it. Thanks!

**Comment by plainspace** [comment]
You can find instructions here: https://support.google.com/chrome_webstore/answer/2664769?hl=en

**Comment by tschaub** [comment]
From the chrome://extensions/, you should be able to manage this and all your extensions.

![image](https://user-images.githubusercontent.com/41094/87487757-bf968f80-c5fb-11ea-99b5-d16c451c172e.png)

You should see options to remove or disable the extension.
