### ISSUE TITLE
Planet Labs Inc -> Planet Labs PBC

### ISSUE THREAD

**Issue by philiplinden** [planetlabs/planet-view#73]
https://github.com/planetlabs/planet-view/blob/f4f78de6654db76f92afad74bb9b8de40dd54d9a/src/index.html#L18

The official name of the company became Planet Labs PBC on [December 7, 2021](https://investors.planet.com/news/news-details/2021/Planet-Announces-Closing-of-Business-Combination-with-dMY-Technology-Group-Inc.-IV/default.aspx).

**Comment by tschaub** [comment]
Thanks, @philiplinden.  Version 2.7.1 of the Chrome extension has been submitted for review.  It looks like Firefox doesn't accept v3 extension manifests, so I didn't update the Firefox extension.  If someone wants to take on building a separate manifest for the Firefox extension, pull requests welcome.
